[2023-04-28T18:00:36.448-0300] {processor.py:153} INFO - Started process (PID=4603) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:00:36.449-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:00:36.450-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:00:36.450-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:00:36.453-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:00:36.452-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:00:36.453-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:00:36.473-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2023-04-28T18:01:17.718-0300] {processor.py:153} INFO - Started process (PID=4645) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:01:17.719-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:01:17.719-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:01:17.719-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:01:17.721-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:01:17.721-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:01:17.721-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:01:17.737-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-28T18:02:26.782-0300] {processor.py:153} INFO - Started process (PID=4748) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:02:26.783-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:02:26.784-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:02:26.784-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:02:26.788-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:02:26.786-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:02:26.788-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:02:26.810-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.031 seconds
[2023-04-28T18:03:14.577-0300] {processor.py:153} INFO - Started process (PID=4841) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:03:14.578-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:03:14.578-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:03:14.578-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:03:14.580-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:03:14.580-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:03:14.580-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:03:14.602-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.030 seconds
[2023-04-28T18:03:58.846-0300] {processor.py:153} INFO - Started process (PID=4883) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:03:58.847-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:03:58.848-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:03:58.848-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:03:58.849-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:03:58.849-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:03:58.850-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:03:58.866-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.022 seconds
[2023-04-28T18:04:35.032-0300] {processor.py:153} INFO - Started process (PID=4922) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:04:35.033-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:04:35.033-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:04:35.033-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:04:35.035-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:04:35.035-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:04:35.035-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:04:35.052-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.022 seconds
[2023-04-28T18:05:23.189-0300] {processor.py:153} INFO - Started process (PID=5071) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:05:23.193-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:05:23.193-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:05:23.193-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:05:23.195-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:05:23.194-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:05:23.195-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:05:23.211-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-28T18:06:06.112-0300] {processor.py:153} INFO - Started process (PID=5116) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:06:06.113-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:06:06.114-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:06:06.113-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:06:06.115-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:06:06.115-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:06:06.115-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:06:06.133-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.023 seconds
[2023-04-28T18:07:00.677-0300] {processor.py:153} INFO - Started process (PID=5163) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:07:00.780-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:07:00.782-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:07:00.781-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:07:00.791-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:07:00.787-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:07:00.792-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:07:01.134-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.460 seconds
[2023-04-28T18:07:47.861-0300] {processor.py:153} INFO - Started process (PID=5303) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:07:47.925-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:07:47.926-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:07:47.925-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:07:47.930-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:07:47.928-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:07:47.931-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:07:52.159-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 4.301 seconds
[2023-04-28T18:08:36.053-0300] {processor.py:153} INFO - Started process (PID=5395) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:08:36.067-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:08:36.068-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:08:36.068-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:08:36.071-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:08:36.070-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:08:36.071-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:08:36.112-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.061 seconds
[2023-04-28T18:09:23.623-0300] {processor.py:153} INFO - Started process (PID=5490) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:09:23.625-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:09:23.626-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:09:23.625-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:09:23.627-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:09:23.627-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:09:23.627-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:09:23.646-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-28T18:10:13.119-0300] {processor.py:153} INFO - Started process (PID=5583) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:10:13.120-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:10:13.121-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:10:13.121-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:10:13.123-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:10:13.122-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:10:13.123-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:10:13.142-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-28T18:11:12.558-0300] {processor.py:153} INFO - Started process (PID=5737) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:11:12.560-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:11:12.561-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:11:12.561-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:11:12.570-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:11:12.568-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:11:12.571-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:11:12.595-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.039 seconds
[2023-04-28T18:12:03.272-0300] {processor.py:153} INFO - Started process (PID=5835) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:12:03.274-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:12:03.275-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:12:03.275-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:12:03.277-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:12:03.276-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:12:03.277-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:12:03.450-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.180 seconds
[2023-04-28T18:13:13.289-0300] {processor.py:153} INFO - Started process (PID=5888) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:13:13.290-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:13:13.291-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:13:13.291-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:13:13.294-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:13:13.293-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:13:13.294-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:13:13.315-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2023-04-28T18:14:04.145-0300] {processor.py:153} INFO - Started process (PID=5933) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:14:04.146-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:14:04.147-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:14:04.147-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:14:04.149-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:14:04.148-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:14:04.149-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:14:04.167-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.023 seconds
[2023-04-28T18:14:54.675-0300] {processor.py:153} INFO - Started process (PID=5974) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:14:54.676-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:14:54.676-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:14:54.676-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:14:54.679-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:14:54.678-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:14:54.679-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:14:54.733-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.061 seconds
[2023-04-28T18:15:54.135-0300] {processor.py:153} INFO - Started process (PID=6075) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:15:54.139-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:15:54.140-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:15:54.140-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:15:54.142-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:15:54.141-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:15:54.142-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:15:54.416-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.284 seconds
[2023-04-28T18:16:51.194-0300] {processor.py:153} INFO - Started process (PID=6124) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:16:51.229-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:16:51.230-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:16:51.230-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:16:51.233-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:16:51.232-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:16:51.233-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:16:51.549-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.357 seconds
[2023-04-28T18:17:50.452-0300] {processor.py:153} INFO - Started process (PID=6174) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:17:50.454-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:17:50.455-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:17:50.454-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:17:50.461-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:17:50.460-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:17:50.462-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:17:50.513-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.063 seconds
[2023-04-28T18:18:34.762-0300] {processor.py:153} INFO - Started process (PID=6218) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:18:34.764-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:18:34.764-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:18:34.764-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:18:34.766-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:18:34.765-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:18:34.766-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:18:34.783-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.023 seconds
[2023-04-28T18:19:17.275-0300] {processor.py:153} INFO - Started process (PID=6257) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:19:17.277-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:19:17.277-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:19:17.277-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:19:17.280-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:19:17.280-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:19:17.281-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:19:17.299-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.028 seconds
[2023-04-28T18:20:04.669-0300] {processor.py:153} INFO - Started process (PID=6301) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:20:04.670-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:20:04.670-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:20:04.670-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:20:04.672-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:20:04.671-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:20:04.672-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:20:04.690-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.023 seconds
[2023-04-28T18:20:55.560-0300] {processor.py:153} INFO - Started process (PID=6398) to work on /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:20:55.588-0300] {processor.py:743} INFO - Processing file /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-28T18:20:55.589-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:20:55.589-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:20:55.592-0300] {logging_mixin.py:137} INFO - [2023-04-28T18:20:55.591-0300] {dagbag.py:341} ERROR - Failed to import: /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-28T18:20:55.592-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-28T18:20:55.844-0300] {processor.py:175} INFO - Processing /home/lcscarv/projetos/indicium/desafio_5/.venv/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 0.286 seconds
